### ISSUE TITLE
Feedback from presentation

### ISSUE THREAD

**Issue by 0xjjpa** [opengsn/workshop2#3]
As [requested](https://twitter.com/opengsn/status/1412103558724558855?s=20), thought on sharing some feedback on the [great presentation](https://www.youtube.com/watch?app=desktop&v=Tb4HKboFmoU&feature=youtu.be)! After watching the entire workshop, here are some recommendations:

- [7:12](https://youtu.be/Tb4HKboFmoU?t=432) Ideally it would be great to show early the [diff](https://github.com/opengsn/workshop/pull/1/files) for the changes when implementing GSN. You mention that afterward, but in case someone wanted to skip the manual changes, that would have been great.
- [14:19](https://youtu.be/Tb4HKboFmoU?t=859) There are too many moving parts IMHO to be sharing there, and maybe some visual aid would have been welcomed. Do I require the paymaster in my contract? Update the provider? Redeploy the relayer? Some time ago I [put together](https://twitter.com/jjperezaguinaga/status/1397337286958780428?s=20) a diagram for showcasing GSN, happy to chip in here and _try_ to visualize all the moving parts so devs know how to change what where.
- [16:47](https://youtu.be/Tb4HKboFmoU?t=1007) Woah, what was that `1 ETH` for? Is that needed as a “deposit” for the relayer?

In general, I really enjoyed the walkthrough, but I do see as a challenge how the average developer will go and overhaul their app into implementing the entire stack. From reading this, I see there are `3` challenges needed for OpenGSN adoption:

- *Reusing existing forwarder*. Requiring only updating `msg.sender` to `_msgSender()` is great, but having to redeploy the contract with a forwarder as a constructor is a bit of a turn-off, because a Forwarder needs to be deployed. What would it take for any contract just to take an existing Forwarder? Does it have to be something the contract owner manages?
- *Automating boilerplate*. My guess is that for 80% of the use cases people will just want a `WhitelistPaymaster` that they can offline manage via some API they can validate off-chain. How hard would it be to have a script deploy one ready to use?
- *Paymaster management*. It seems that for the UI to work we need to have a wrapped Paymaster and the RelayProvider, the former having set up the RelayHub and trusted Forwarder address. Is there a roadmap or feature request to allow the creation of tooling to manage these Paymaster contracts? For the average UI guy they just want to update their Metamask modal and go to some dashboard to fund calls for whitelisted addresses. If none exists, are there any existing grants on Gitcoin or similar to be able to contribute to?

Very excited about the project! Take the feedback as a grain of salt and don't hesitate to [ping me in Twitter](https://twitter.com/jjperezaguinaga) if I can help somehow.

**Comment by drortirosh** [comment]
Thank you very much for your feedback. Sorry for not getting earlier back to you.
We will try to incorporate these issues into the tutorial video.

re: eth deposit - the paymaster pays with its deposit to the paymaster. It can withdraw this value anytime (using `withdrawRelayHubDepositTo()`) the deposited amount can be anything you're comfortable with.

- Forwarder as constructor param: a contract is required to know its forwarder in order to work. its either a constructor parameter, or a setter functions (which also implies the contract is ownable - which is also acceptable).
- boilerplate: very interesting idea. Once we see some use-cases, we can add scripts to automate them.
- paymaster management: indeed, such a tool would be nice, though for the simplest use case (fund the paymaster) you can simply point your metamask at it, and transfer funds.

**Comment by 0xjjpa** [comment]
@drortirosh No worries! Jumping into this thread since we already opened the conversation.

* re: Forwarder, I'm going to try using a proxy contract in between an existing contract which would take `_msgSender()` and see if I can get some traction like that.
* I'm actually going to try that for [a project where users submit EIP-712 permits for relay](https://github.com/hoprnet/hopr-leaderboard/issues/148), in this case to a very [simple contract](https://github.com/ETHPoster/contract/blob/master/contracts/Poster.sol) which uses `msg.sender` so likely will have to prepend a proxy contract that would call the original one.
* My uses case is allowing [Poster](https://poster-app.on.fleek.co/)'s users to pay for other people's gas costs, which means that I would need to deploy GSN on _their_ behalf that _they_ need to manage. I'll toy with this concept and see if I produce any tooling we can reuse.

Let's hope we can get OpenGSN to a point it's as easy as [this](https://github.com/m1guelpf/wagmipet-frontend/blob/main/src/pages/pet/%5BtokenID%5D.tsx#L47) to call a Relayer, and a few clicks to deploy and fund the Paymaster.
