### ISSUE TITLE
Workshop with paymaster: Error: Rejected relayTransaction call with reason: Cannot read properties of undefined (reading 'contract')

### ISSUE THREAD

**Issue by NumairFazili** [opengsn/workshop2#4]
Facing an issue with the whitelist paymaster, the program throws an exception Uncaught (in promise) Error: Rejected relayTransaction call with reason: Cannot read properties of undefined (reading 'contract'). 

Initially, I was following the youtube tutorial but cloned the paymaster pull request upon encountering this issue. However, the error persists.

For reference, this was the console output prior to the error: 

CaptureTheFlag contract 0x0E696947A06550DEf604e82C26fd9E493e576337

identified network: {"chainId":1337,"name":"unknown"}

calling sendAsync{"method":"eth_sendTransaction","params":
[{"gas":"0xb0a4","from":"0xffcf8fdee72ac11b5c542428b35eef5769c409f0","to":"0x0e696947a06550def604e82c26fd9e493e576337","data":"0x239e26f2"}],"id":11,"jsonrpc":"2.0"}

Rejected relayTransaction call with reason: Cannot read properties of undefined (reading 'contract')

**Comment by alxiong** [comment]
Confirm, I can reproduce the same error (all deployments are fine, we also imported the private key of the first account from ganache into our metamask, we confirm to connect to the correct localhost network on MetaMask. Error occur when you click on  "Capture the Flag" button):

<img width="1285" alt="Screenshot 2021-10-15 at 11 55 35 AM" src="https://user-images.githubusercontent.com/20514086/137429837-fea97a18-07a8-46f5-9a94-af888ee29daf.png">

@drortirosh
